const ActionTypesBooking = {
    REQ_GET_ALL_LIST_BOOKING: 'REQ_GET_ALL_LIST_BOOKING',
    RES_GET_ALL_LIST_BOOKING: 'RES_GET_ALL_LIST_BOOKING',
    REQ_GET_ONE_BOOKING: 'REQ_GET_ONE_BOOKING',
    RES_GET_ONE_BOOKING: 'RES_GET_ONE_BOOKING',
    REQ_GET_ALL_FACILITIES_SUPPORT: 'REQ_GET_ALL_FACILITIES_SUPPORT',
    RES_GET_ALL_FACILITIES_SUPPORT: 'RES_GET_ALL_FACILITIES_SUPPORT',
    REQ_GET_OTHER_ROOMS: 'REQ_GET_OTHER_ROOMS',
    RES_GET_OTHER_ROOMS: 'RES_GET_OTHER_ROOMS',
    REQ_CREATE_TEMPORARY_BORDE: 'REQ_CREATE_TEMPORARY_BORDE',
    RES_CREATE_TEMPORARY_BORDE: 'RES_CREATE_TEMPORARY_BORDE',
    REQ_GET_ONE_DETAIL_PEMBAYARAN_BOOKING: 'REQ_GET_ONE_DETAIL_PEMBAYARAN_BOOKING',
    RES_GET_ONE_DETAIL_PEMBAYARAN_BOOKING: 'RES_GET_ONE_DETAIL_PEMBAYARAN_BOOKING',
}

export default ActionTypesBooking
