const ActionTypes = {
  //   VENDOR
  REQUEST_GET_VENDOR: "REQUEST_GET_VENDOR",
  GET_VENDOR_RESPONSE: "GET_VENDOR_RESPONSE",
  REQUEST_ADD_VENDOR: "REQUEST_ADD_VENDOR",
  GET_ADD_VENDOR_RESPONSE: "GET_ADD_VENDOR_RESPONSE",
  REQUEST_UPDATE_VENDOR: "REQUEST_UPDATE_VENDOR",
  GET_UPDATE_VENDOR_RESPONSE: "GET_UPDATE_VENDOR_RESPONSE",
  REQUEST_DELETE_VENDOR: "REQUEST_DELETE_VENDOR",
  GET_DELETE_VENDOR_RESPONSE: "GET_DELETE_VENDOR_RESPONSE",
  SEARCH_VENDOR_REQUEST: "SEARCH_VENDOR_REQUEST",
  SEARCH_VENDOR_RESPONSE: "SEARCH_VENDOR_RESPONSE",

  // PRODUCT VENDOR
  REQUEST_GET_VENDOR_PROD: "REQUEST_GET_VENDOR_PROD",
  GET_VENDOR_PROD: "GET_VENDOR_PROD",
  REQUEST_ADD_VENDOR_PROD: "REQUEST_ADD_VENDOR_PROD",
  GET_VENDOR_PROD_RESPONSE: "GET_VENDOR_PROD_RESPONSE",
  REQUEST_UPDATE_VENDOR_PROD: "REQUEST_UPDATE_VENDOR_PROD",
  UPDATE_VENDOR_PROD_RESPONSE: "UPDATE_VENDOR_PROD_RESPONSE",
  REQUEST_DELETE_VENDOR_PROD: "REQUEST_DELETE_VENDOR_PROD",
  DELETE_VENDOR_PROD_RESPONSE: "DELETE_VENDOR_PROD_RESPONSE",

  //   STOCK
  REQUEST_GET_STOCK: "REQUEST_GET_STOCK",
  GET_STOCK_RESPONSE: "GET_STOCK_RESPONSE",
  REQUEST_ADD_STOCK: "REQUEST_ADD_STOCK",
  ADD_STOCK_RESPONSE: "ADD_STOCK_RESPONSE",
  REQUEST_UPDATE_STOCK: "REQUEST_UPDATE_STOCK",
  UPDATE_STOCK_RESPONSE: "UPDATE_STOCK_RESPONSE",
  REQUEST_DELETE_STOCK: "REQUEST_DELETE_STOCK",
  DELETE_STOCK_RESPONSE: "DELETE_STOCK_RESPONSE",
  REQUEST_GET_LIST_STOCK: "REQUEST_GET_LIST_STOCK",
  GET_LIST_STOCK_RESPONSE: "GET_LIST_STOCK_RESPONSE",

  REQUEST_GET_STOD: "REQUEST_GET_STOD",
  GET_STOD_RESPONSE: "GET_STOD_RESPONSE",

  //   LIST ORDER
  REQUEST_GET_LIST_ORDER: "REQUEST_GET_LIST_ORDER",
  GET_LIST_ORDER_RESPONSE: "GET_LIST_ORDER_RESPONSE",
  REQUEST_UPDATE_LIST_ORDER: "REQUEST_UPDATE_LIST_ORDER",
  UPDATE_LIST_ORDER_RESPONSE: "UPDATE_LIST_ORDER_RESPONSE",
  REQUEST_DEL_LIST_ORDER: "REQUEST_DEL_LIST_ORDER",
  DEL_LIST_ORDER_RESPONSE: "DEL_LIST_ORDER_RESPONSE",

  //   ORDER DETAIL
  REQUEST_GET_ORDER_DETAIL: "REQUEST_GET_ORDER_DETAIL",
  GET_ORDER_DETAIL_RESPONSE: "GET_ORDER_DETAIL_RESPONSE",
};

export default ActionTypes;
