const ActionTypes = {
  // ================Region============//
  UPDATE_REGION: "UPDATE_REGION",
  UPDATE_REGION_RESPONSE: "UPDATE_REGION_RESPONSE",
  REQ_GET_REGION: "REQ_GET_REGION",
  GET_REGION_RESPONSE: "GET_REGION_RESPONSE",
  ADD_REGION: "ADD_REGION",
  ADD_REGION_RESPONSE: "ADD_REGION_RESPONSE",
  DEL_REGION: "DEL_REGION",
  DEL_REGION_RESPONSE: "DEL_REGION_RESPONSE",

  //===============Country===============//
  UPDATE_COUNTRY: "UPDATE_COUNTRY",
  UPDATE_COUNTRY_RESPONSE: "UPDATE_COUNTRY_RESPONSE",
  REQ_GET_COUNTRY: "REQ_GET_COUNTRY",
  GET_COUNTRY_RESPONSE: "GET_COUNTRY_RESPONSE",
  REQ_GET_COUNTRYBYREGION: "REQ_GET_COUNTRYBYREGION",
  GET_COUNTRYBYREGION_RESPONSE: "GET_COUNTRYBYREGION_RESPONSE",
  ADD_COUNTRY: "ADD_COUNTRY",
  ADD_COUNTRY_RESPONSE: "ADD_COUNTRY_RESPONSE",
  DEL_COUNTRY: "DEL_COUNTRY",
  DEL_COUNTRY_RESPONSE: "DEL_COUNTRY_RESPONSE",

  //=============Province===============//
  UPDATE_PROVINCE: "UPDATE_PROVINCE",
  UPDATE_PROVINCE_RESPONSE: "UPDATE_PROVINCE_RESPONSE",
  REQ_GET_PROVINCE: "REQ_GET_PROVINCE",
  GET_PROVINCE_RESPONSE: "GET_PROVINCE_RESPONSE",
  REQ_GET_PROVINCEBYCOUNTRY: "REQ_GET_PROVINCEBYCOUNTRY",
  GET_PROVINCEBYCOUNTRY_RESPONSE: "GET_PROVINCEBYCOUNTRY_RESPONSE",
  ADD_PROVINCE: "ADD_PROVINCE",
  ADD_PROVINCE_RESPONSE: "ADD_PROVINCE_RESPONSE",
  DEL_PROVINCE: "DEL_PROVINCE",
  DEL_PROVINCE_RESPONSE: "DEL_PROVINCE_RESPONSE",

  //==============City===================//
  UPDATE_CITY: "UPDATE_CITY",
  UPDATE_CITY_RESPONSE: "UPDATE_CITY_RESPONSE",
  REQ_GET_CITY: "REQ_GET_CITY",
  GET_CITY_RESPONSE: "GET_CITY_RESPONSE",
  REQ_GET_CITYBYPROVINCE: "REQ_GET_CITYBYPROVINCE",
  GET_CITYBYPROVINCE_RESPONSE: "GET_CITYBYPROVINCE_RESPONSE",
  ADD_CITY: "ADD_CITY",
  ADD_CITY_RESPONSE: "ADD_CITY_RESPONSE",
  DEL_CITY: "DEL_CITY",
  DEL_CITY_RESPONSE: "DEL_CITY_RESPONSE",

  //==============Address===================//
  UPDATE_ADDRESS: "UPDATE_ADDRESS",
  UPDATE_ADDRESS_RESPONSE: "UPDATE_ADDRESS_RESPONSE",
  REQ_GET_ADDRESS: "REQ_GET_ADDRESS",
  GET_ADDRESS_RESPONSE: "GET_ADDRESS_RESPONSE",
  REQ_GET_ADDRESSBYCITY: "REQ_GET_ADDRESSBYCITY",
  GET_ADDRESSBYCITY_RESPONSE: "GET_ADDRESSBYCITY_RESPONSE",
  ADD_ADDRESS: "ADD_ADDRESS",
  ADD_ADDRESS_RESPONSE: "ADD_ADDRESS_RESPONSE",
  DEL_ADDRESS: "DEL_ADDRESS",
  DEL_ADDRESS_RESPONSE: "DEL_ADDRESS_RESPONSE",

  //===============Policy==============//
  UPDATE_POLICY: "UPDATE_POLICY",
  UPDATE_POLICY_RESPONSE: "UPDATE_POLICY_RESPONSE",
  REQ_GET_POLICY: "REQ_GET_POLICY",
  GET_POLICY_RESPONSE: "GET_POLICY_RESPONSE",
  ADD_POLICY: "ADD_POLICY",
  ADD_POLICY_RESPONSE: "ADD_POLICY_RESPONSE",
  DEL_POLICY: "DEL_POLICY",
  DEL_POLICY_RESPONSE: "DEL_POLICY_RESPONSE",

  //=============CategoryGroup==========//
  UPDATE_CATEGORYGROUP: "UPDATE_CATEGORYGROUP",
  UPDATE_CATEGORYGROUP_RESPONSE: "UPDATE_CATEGORYGROUP_RESPONSE",
  REQ_GET_CATEGORYGROUP: "REQ_GET_CATEGORYGROUP",
  GET_CATEGORYGROUP_RESPONSE: "GET_CATEGORYGROUP_RESPONSE",
  ADD_CATEGORYGROUP: "ADD_CATEGORYGROUP",
  ADD_CATEGORYGROUP_RESPONSE: "ADD_CATEGORYGROUP_RESPONSE",
  DEL_CATEGORYGROUP: "DEL_CATEGORYGROUP",
  DEL_CATEGORYGROUP_RESPONSE: "DEL_CATEGORYGROUP_RESPONSE",

  //==============PriceItems============//
  UPDATE_PRICEITEMS: "UPDATE_PRICEITEMS",
  UPDATE_PRICEITEMS_RESPONSE: "UPDATE_PRICEITEMS_RESPONSE",
  REQ_GET_PRICEITEMS: "REQ_GET_PRICEITEMS",
  GET_PRICEITEMS_RESPONSE: "GET_PRICEITEMS_RESPONSE",
  ADD_PRICEITEMS: "ADD_PRICEITEMS",
  ADD_PRICEITEMS_RESPONSE: "ADD_PRICEITEMS_RESPONSE",
  DEL_PRICEITEMS: "DEL_PRICEITEMS",
  DEL_PRICEITEMS_RESPONSE: "DEL_PRICEITEMS_RESPONSE",

  // ==============ServiceTask==========//
  REQ_GET_SERVICETASK: "REQ_GET_SERVICETASK",
  GET_SERVICETASK_RESPONSE: "GET_SERVICETASK_RESPONSE",
  UPDATE_SERVICETASK: "UPDATE_SERVICETASK",
  UPDATE_SERVICETASK_RESPONSE: "UPDATE_SERVICETASK_RESPONSE",
  ADD_SERVICETASK: "ADD_SERVICETASK",
  ADD_SERVICETASK_RESPONSE: "ADD_SERVICETASK_RESPONSE",
  DEL_SERVICETASK: "DEL_SERVICETASK",
  DEL_SERVICETASK_RESPONSE: "DEL_SERVICETASK_RESPONSE",
};
export default ActionTypes;
