const ActionTypesUsers = {
  REQ_GET_LOGIN: "REQ_GET_LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REQ_LOGOUT: "REQ_LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REQ_REGISTER: "REQ_REGISTER",
  REGISTER_FAILED: "REGISTER_FAILED",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REQ_LOGIN_GUEST: "REQ_LOGIN_GUEST",
};

export default ActionTypesUsers;
