const ActionTypesUsers = {
  REQ_GET_LOGIN: "REQ_GET_LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REQ_LOGOUT: "REQ_LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  REQ_REGISTER: "REQ_REGISTER",
  REGISTER_FAILED: "REGISTER_FAILED",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REQ_LOGIN_GUEST: "REQ_LOGIN_GUEST",
  REQ_REGISTER_GUEST: "REQ_REGISTER_GUEST",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILED: "UPDATE_PROFILE_FAILED",
  UPDATE_PASSWORD: "UPDATE_PASSWORD",
  UPDATE_PASSWORD_SUCCESS: "UPDATE_PASSWORD_SUCCESS",
  UPDATE_PASSWORD_FAILED: "UPDATE_PASSWORD_FAILED",
};

export default ActionTypesUsers;
