const actionTypes = {
  //* RESTO_MENUS
  GET_REME_RESPONSE: 'GET_REME_RESPONSE',
  REQ_GET_REME: 'REQ_GET_REME',
  ADD_REME: 'ADD_REME',
  ADD_REME_RESPONSE: 'ADD_REME_RESPONSE',
  UPDATE_REME: 'UPDATE_REME',
  UPDATE_REME_RESPONSE: 'UPDATE_REME_RESPONSE',
  DEL_REME: 'DEL_REME',
  DEL_REME_RESPONSE: 'DEL_REME_RESPONSE',
  SEARCH_REME: 'SEARCH_REME',
  SEARCH_REME_RESPONSE: 'SEARCH_VENDOR_RESPONSE',
  SORT_REME: 'SORT_REME',
  SORT_REME_RESPONSE: 'SORT_REME_RESPONSE',

  //* RESTO_MENU_PHOTOS
  GET_REPHO_RESPONSE: 'GET_REPHO_RESPONSE',
  REQ_GET_REPHO: 'REQ_GET_REPHO',
  ADD_REPHO: 'ADD_REPHO',
  ADD_REPHO_RESPONSE: 'ADD_REPHO_RESPONSE',
  UPDATE_REPHO: 'UPDATE_REPHO',
  UPDATE_REPHO_RESPONSE: 'UPDATE_REPHO_RESPONSE',
  DEL_REPHO: 'DEL_REPHO',
  DEL_REPHO_RESPONSE: 'DEL_REPHO_RESPONSE',

  // * ORDER_MENUS
  GET_ORME_RESPONSE: 'GET_ORME_RESPONSE',
  REQ_GET_ORME: 'REQ_GET_ORME',
  ADD_ORME: 'ADD_ORME',
  ADD_ORME_RESPONSE: 'ADD_ORME_RESPONSE',
  UPDATE_ORME: 'UPDATE_ORME',
  UPDATE_ORME_RESPONSE: 'UPDATE_ORME_RESPONSE',
  DEL_ORME: 'DEL_ORME',
  DEL_ORME_RESPONSE: 'DEL_ORME_RESPONSE',

  // * ORDER_MENU_DETAIL
  GET_ORDET_RESPONSE: 'GET_ORDET_RESPONSE',
  REQ_GET_ORDET: 'REQ_GET_ORDET',
  ADD_ORDET: 'ADD_ORDET',
  ADD_ORDET_RESPONSE: 'ADD_ORDET_RESPONSE',
  UPDATE_ORDET: 'UPDATE_ORDET',
  UPDATE_ORDET_RESPONSE: 'UPDATE_ORDET_RESPONSE',
  DEL_ORDET: 'DEL_ORDET',
  DEL_ORDET_RESPONSE: 'DEL_ORDET_RESPONSE',
}

export default actionTypes
