const actionType = {

// =======BANK===========
    GET_BANK:'GET_BANK',
    GET_BANK_RESPONSE:'GET_BANK_RESPONSE',
    ADD_BANK:'ADD_BANK',
    ADD_BANK_RESPONSE:'ADD_BANK_RESPONSE',
    UPDATE_BANK:'UPDATE_BANK',
    UPDATE_BANK_RESPONSE:'UPDATE_BANK_RESPONSE',
    DEL_BANK:'DEL_BANK',
    DEL_BANK_RESPONSE:'DEL_BANK_RESPONSE',

// =======FINTECH========
    GET_FINTECH:'GET_FINTECH',
    GET_FINTECH_RESPONSE:'GET_FINTECH_RESPONSE',
    ADD_FINTECH:'ADD_FINTECH',
    ADD_FINTECH_RESPONSE:'ADD_FINTECH_RESPONSE',
    UPDATE_FINTECH:'UPDATE_FINTECH',
    UPDATE_FINTECH_RESPONSE:'UPDATE_FINTECH_RESPONSE',
    DEL_FINTECH:'DEL_FINTECH',
    DEL_FINTECH_RESPONSE:'DEL_FINTECH_RESPONSE',


// ===========USERACCOUNT=================
    GET_USER_ACCOUNT:'GET_USER_ACCOUNT',
    GET_USER_ACCOUNT_RESPONSE:'GET_USER_ACCOUNT_RESPONSE',
    ADD_USER_ACCOUNT:'ADD_USER_ACCOUNT',
    ADD_USER_ACCOUNT_RESPONSE:'ADD_USER_ACCOUNT_RESPONSE',
    UPDATE_USER_ACCOUNT:'UPDATE_USER_ACCOUNT',
    UPDATE_USER_ACCOUNT_RESPONSE:'UPDATE_USER_ACCOUNT_RESPONSE',
    DEL_USER_ACCOUNT:'DEL_USER_ACCOUNT',
    DEL_USER_ACCOUNT_RESPONSE:'DEL_USER_ACCOUNT_RESPONSE',
    GET_BANK_FINTECH:'GET_BANK_FINTECH',
    GET_BANK_FINTECH_RESPONSE:'GET_BANK_FINTECH_RESPONSE',
    

// ========PAYMENT-TRANSACTION===================
    GET_PAYMENT_TRANSACTION:'GET_PAYMENT_TRANSACTION',
    GET_PAYMENT_TRANSACTION_RESPONSE:'GET_PAYMENT_TRANSACTION_RESPONSE',
    POST_TOPUP:'POST_TOPUP',
    POST_TOPUP_RESPONSE:'POST_TOPUP_RESPONSE',
    

}

export default actionType