const ActionTypes = {
  // === DEPARTMENT === //
  REQUEST_GET_DEPARTMENT: "REQUEST_GET_DEPARTMENT",
  GET_DEPARTMENT_RESPONSE: "GET_DEPARTMENT_RESPONSE",

  REQUEST_ADD_DEPARTMENT: "REQUEST_ADD_DEPARTMENT",
  ADD_DEPARTMENT_RESPONSE: "ADD_DEPARTMENT_RESPONSE",

  REQUEST_UPDATE_DEPARTMENT: "REQUEST_UPDATE_DEPARTMENT",
  UPDATE_DEPARTMENT_RESPONSE: "UPDATE_DEPARTMENT_RESPONSE",

  REQUEST_DELETE_DEPARTMENT: "REQUEST_DELETE_DEPARTMENT",
  DELETE_DEPARTMENT_RESPONSE: "DELETE_DEPARTMENT_RESPONSE",

  // === EMPLOYEE === //
  REQUEST_GET_EMPLOYEE: "REQUEST_GET_EMPLOYEE",
  GET_EMPLOYEE_RESPONSE: "GET_EMPLOYEE_RESPONSE",

  REQUEST_ADD_EMPLOYEE: "REQUEST_ADD_EMPLOYEE",
  ADD_EMPLOYEE_RESPONSE: "ADD_EMPLOYEE_RESPONSE",

  REQUEST_UPDATE_EMPLOYEE: "REQUEST_UPDATE_EMPLOYEE",
  UPDATE_EMPLOYEE_RESPONSE: "UPDATE_EMPLOYEE_RESPONSE",

  REQUEST_DELETE_EMPLOYEE: "REQUEST_DELETE_EMPLOYEE",
  DELETE_EMPLOYEE_RESPONSE: "DELETE_EMPLOYEE_RESPONSE",

  // === WORK ORDERS === //
  REQUEST_GET_WORKORDERS: "REQUEST_GET_WORKORDERS",
  GET_WORKORDERS_RESPONSE: "GET_WORKORDERS_RESPONSE",

  REQUEST_ADD_WORKORDERS: "REQUEST_ADD_WORKORDERS",
  ADD_WORKORDERS_RESPONSE: "ADD_WORKORDERS_RESPONSE",

  REQUEST_UPDATE_WORKORDERS: "REQUEST_UPDATE_WORKORDERS",
  UPDATE_WORKORDERS_RESPONSE: "UPDATE_WORKORDERS_RESPONSE",

  REQUEST_DELETE_WORKORDERS: "REQUEST_DELETE_WORKORDERS",
  DELETE_WORKORDERS_RESPONSE: "DELETE_WORKORDERS_RESPONSE",

  // === WORK ORDER DETAIL === //
  REQUEST_GET_WORKORDERDETAIL: "REQUEST_GET_WORKORDERDETAIL",
  GET_WORKORDERDETAIL_RESPONSE: "GET_WORKORDERDETAIL_RESPONSE",

  REQUEST_ADD_WORKORDERDETAIL: "REQUEST_ADD_WORKORDERDETAIL",
  ADD_WORKORDERDETAIL_RESPONSE: "ADD_WORKORDERDETAIL_RESPONSE",

  REQUEST_UPDATE_WORKORDERDETAIL: "REQUEST_UPDATE_WORKORDERDETAIL",
  UPDATE_WORKORDERDETAIL_RESPONSE: "UPDATE_WORKORDERDETAIL_RESPONSE",

  REQUEST_DELETE_WORKORDERDETAIL: "REQUEST_DELETE_WORKORDERDETAIL",
  DELETE_WORKORDERDETAIL_RESPONSE: "DELETE_WORKORDERDETAIL_RESPONSE",

  // === EMPLOYEE PAY HISTORY === //
  REQUEST_GET_EMPOLYEEPAYHISTORY: "REQUEST_GET_EMPOLYEEPAYHISTORY",
  GET_EMPLOYEEPAYHISTORY_RESPONSE: "GET_EMPLOYEEPAYHISTORY_RESPONSE",

  REQUEST_ADD_EMPOLYEEPAYHISTORY: "REQUEST_ADD_EMPOLYEEPAYHISTORY",
  ADD_EMPLOYEEPAYHISTORY_RESPONSE: "ADD_EMPLOYEEPAYHISTORY_RESPONSE",

  REQUEST_UPDATE_EMPOLYEEPAYHISTORY: "REQUEST_UPDATE_EMPOLYEEPAYHISTORY",
  UPDATE_EMPLOYEEPAYHISTORY_RESPONSE: "UPDATE_EMPLOYEEPAYHISTORY_RESPONSE",

  REQUEST_DELETE_EMPOLYEEPAYHISTORY: "REQUEST_DELETE_EMPOLYEEPAYHISTORY",
  DELETE_EMPLOYEEPAYHISTORY_RESPONSE: "DELETE_EMPLOYEEPAYHISTORY_RESPONSE",

  // === EMPLOYEE DEPARTMENT HISTORY === //
  REQUEST_GET_EMPOLYEEDEPARTMENTHISTORY: "REQUEST_GET_EMPOLYEEDEPARTMENTHISTORY",
  GET_EMPOLYEEDEPARTMENTHISTORY_RESPONSE: "GET_EMPOLYEEDEPARTMENTHISTORY_RESPONSE",

  REQUEST_ADD_EMPOLYEEDEPARTMENTHISTORY: "REQUEST_ADD_EMPOLYEEDEPARTMENTHISTORY",
  ADD_EMPOLYEEDEPARTMENTHISTORY_RESPONSE: "ADD_EMPOLYEEDEPARTMENTHISTORY_RESPONSE",

  REQUEST_UPDATE_EMPOLYEEDEPARTMENTHISTORY: "REQUEST_UPDATE_EMPOLYEEDEPARTMENTHISTORY",
  UPDATE_EMPOLYEEDEPARTMENTHISTORY_RESPONSE: "UPDATE_EMPOLYEEDEPARTMENTHISTORY_RESPONSE",

  REQUEST_DELETE_EMPOLYEEDEPARTMENTHISTORY: "REQUEST_DELETE_EMPOLYEEDEPARTMENTHISTORY",
  DELETE_EMPOLYEEDEPARTMENTHISTORY_RESPONSE: "DELETE_EMPOLYEEDEPARTMENTHISTORY_RESPONSE",
};

export default ActionTypes;
